
ATD7014533381// GSM MAKE CALL TO THAT TYPED NUMBER
ATH// GSM REJECT THE CALL TO THAT NUMBER
AT+CLIP=1 //WHEN WE CALL ON GSM THAN IT SHOWS OUR CALLER ID ALONG WITH OUR NAME IF WE ARE IN CONTACTS
ATA//GSM ACCEPTS THE CALL WHEN WE MAKE CALL TO GSM
AT+CMGL="ALL"//TO SEE ALL MESSAGE ARRIVED ON GSM SIM
AT+CMGR=1//TO READ 1ST MESSAGE FROM INBOX OF GSM SIM
AT+CMGR=2//TO READ 2ND MESSAGE FROM INBOX OF GSM SIM AND SO ON...

AT+CMGF=1//GSM IN TEXT MODE
AT+CMGS="+7014533381"//SEND SMS TO THAT TYPED NUMBER
CTRL+Z//TO SEND ABOVE SMS (char)26
AT+CNMI=2,2,0,0,0//NOW GSM IS READY TO TAKE SMS FROM MOBILE




